export interface ForecastData {
    day: "TODAY" | "TOMORROW" | "AFTER_TOMORROW" | string;
    time: "AM_3" | "AM_6" | "AM_9" | "AM_12" | "PM_3" | "PM_6" | "PM_9" | "PM_12" | string;
    dewPointC: number;
    dewPointF: number;
    feelsLikeC: number;
    feelsLikeF: number;
    eatIndexC: number;
    heatIndexF: number;
    windChillC: number;
    windChillF: number;
    windGustKmph: number;
    windGustMiles: number;
    chanceOfFog: number;
    chanceOfFrost: number;
    chanceOfHighTemperature: number;
    chanceOfOvercast: number;
    chanceOfRain: number;
    chanceOfRemdry: number;
    chanceOfSnow: number;
    chanceOfSunshine: number;
    chanceOfThunder: number;
    chanceOfWindy: number;
    cloudCover: number;
    humidity: number;
    precipInches: number;
    precipMM: number;
    pressure: number;
    pressureInches: number;
    temperatureC: number;
    temperatureF: number;
    timeInHundreds: number;
    uvIndex: number;
    visibility: number;
    visibilityMiles: number;
    weatherCode: number;
    weatherDescription: string;
    windDir16Point: string;
    windDirDegree: number;
    windSpeedKmph: number;
    windSpeedMiles: number;
}